### ISSUE TITLE
Implementation of Sorting Algorithms for Visualization 

### ISSUE THREAD

**Issue by Swayam-Hingu** [MSTC-DA-IICT/Hacktoberfest23-PythonCraft-AdvanceEdition#4]
#### Visualize Sorting Algorithms
- Implement the `bubble_sort` function to visualize the bubble sort algorithm.
- Implement the `insertion_sort` function to visualize the insertion sort algorithm.

**Comment by Devdeep-J-S** [comment]
I want to work on this issue. Kindly assign it to me.

**Comment by shashank-u03** [comment]
@Devdeep-J-S Start working on this issue. The deadline to solve this issue will be 2 days. Happy grinding 😃🚀🚀
